### ISSUE TITLE
Switch to unic-langid

### ISSUE THREAD

**Issue by zbraniecki** [magiclen/rocket-accept-language#1]
Hi!

Just a drive-by note that I separated out the language identifier parsing into `unic-langid` and `unic-locale`.

**Comment by magiclen** [comment]
Hi, thanks for your notification. This crate is using `unic-langid` now.

**Comment by zbraniecki** [comment]
cool! I noticed you use a macro to construct it! We also provide `features = ["macros"]` which enables a proc macro that validates the language identifier and deconstructs it:

```rust
use unic_langid::langid;

let en_us = langid!("en-US");
```
